
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mock-apis
  name: mock-apis
  namespace: default
spec:
  selector:
    matchLabels:
      app: mock-apis
  replicas: 1
  template:
    metadata:
      labels:
        app: mock-apis
    spec:
      containers:
      - image: kcbabo/mock-apis:latest
        name: mock-apis
        ports:
        - containerPort: 5000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mock-apis
  namespace: default
  labels:
    service: mock-apis
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: mock-apis
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - routeAction:
        single:
          upstream:
            name: default-mock-apis-5000
            namespace: gloo-system
    - routeAction:
        single:
          upstream:
            name: default-mock-apis-5000
            namespace: gloo-system
      matchers:
        - prefix: "/tracks"
      options:
        waf:
          disabled: true
        dlp:
          enabledFor: ACCESS_LOGS
          actions:
            - actionType: CUSTOM # CUSTOM is the default, so it's not necessary to put the actionType here
              customAction:
                name: api-key
                maskChar: "Y"
                percent:
                  value: 25
                regexActions:
                  - regex: api-key:? *([^\\n]*)(?:\\n)
                    subgroup: 1
            - actionType: KEYVALUE
              keyValueAction:
                keyToMask: api-key
                maskChar: "*"
                name: api-key   # only used for logging
                percent:
                  value: 25  # % of regex match to mask